package hbs.hotelstaff.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBDocument
@DynamoDBTable(tableName = "hotel_staff")
public class HotelStaffDTO {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private Long staffId;

	@DynamoDBAttribute
	private String loginName;

	@DynamoDBAttribute
	private String name;

	@DynamoDBAttribute
	private String password;

	@DynamoDBAttribute
	private String role;

}
